name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build-website:
    defaults:
      run:
        working-directory: ./website
    name: Build website
    # CD workflow already builds and deploys the website for pushes to master, no need to do it twice.
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

  run-prettier:
    name: Run Prettier on code
    # Don't run Prettier for pull requests, only on pushes.
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Prettier on code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write **/*.{md,json,js,css,yaml,yml}
          commit_message: 'style(*): run prettier on codebase'

  check-syntax:
    name: Check template syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check template syntax
        uses: jo3-l/action-check-yag-tmpl-syntax@v2
        with:
          include: '**/*.go.tmpl'
